apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-pgdata
  namespace: group-10
spec:
  storageClassName: csi-cinder-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
