apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: group-10
type: Opaque
stringData:
  CATALOGUE_DB: catalogue_db
  CATALOGUE_USER: catalogue_user
  CATALOGUE_PASSWORD: catalogue_pass
  BOOKING_DB: booking_db
  BOOKING_USER: booking_user
  BOOKING_PASSWORD: booking_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: group-10
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBIT_USER: guest
  RABBIT_PASSWORD: guest
