apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gestione-risorse
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gestione-risorse
    app.kubernetes.io/managed-by: argocd
spec:
  project: maria
  source:
    repoURL: https://github.com/AklMaria/gestione-risorse-fe.git
    targetRevision: iac
    path: deployment_new_argocd/gestione-risorse-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: group-10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
