apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure.fullname" . }}-catalogue-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue-postgres
spec:
  selector:
    {{- include "infrastructure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue-postgres
  ports:
    - port: 5432
      targetPort: 5432
