apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure.fullname" . }}-booking-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: booking-rabbitmq
spec:
  selector:
    {{- include "infrastructure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: booking-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
