apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infrastructure.fullname" . }}-postgres-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
type: Opaque
stringData:
  CATALOGUE_DB: {{ .Values.global.secrets.catalogueDb }}
  CATALOGUE_USER: {{ .Values.global.secrets.catalogueUser }}
  CATALOGUE_PASSWORD: {{ .Values.global.secrets.cataloguePass }}
  BOOKING_DB: {{ .Values.global.secrets.bookingDb }}
  BOOKING_USER: {{ .Values.global.secrets.bookingUser }}
  BOOKING_PASSWORD: {{ .Values.global.secrets.bookingPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infrastructure.fullname" . }}-rabbitmq-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.global.secrets.rabbitUser }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.global.secrets.rabbitPass }}
  RABBIT_USER: {{ .Values.global.secrets.rabbitUser }}
  RABBIT_PASSWORD: {{ .Values.global.secrets.rabbitPass }}
