apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: group-10
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBIT_USER: guest
  RABBIT_PASSWORD: guest
